name: CI (React build + Docker check)

on:
  pull_request:
  push:
    branches: ["dev"]

jobs:
  react-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm ci --legacy-peer-deps --fetch-retries=5 --fetch-retry-maxtimeout=60000

      - name: Run tests
        run: npm test -- --coverage --watchAll=false

      - name: Build React app
        env:
          REACT_APP_AWS_REGION: ${{ secrets.REACT_APP_AWS_REGION }}
          REACT_APP_AWS_ACCESS_KEY_ID: ${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}
          REACT_APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}
          REACT_APP_S3_BUCKET_NAME: ${{ secrets.REACT_APP_S3_BUCKET_NAME }}
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
          if-no-files-found: error

  docker-build-check:
    runs-on: ubuntu-latest
    needs: react-build-test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      - uses: docker/setup-buildx-action@v3

      - name: Build docker image (test only)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: react-ci:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
